function fig_style(Fontsize)
    set(gca, ...
        'TickLabelInterpreter','latex', ...
        'FontSize',Fontsize, ...
        'LineWidth',1, ...
        'Color','none', ...
        'XMinorTick','on', ...
        'YMinorTick','on', ...
        'TickLength', ...
        [1 2]*0.05)
    % pbaspect([1 1 1])
end

