clc
clear
close all

addpath(genpath('src/'));
run('src/config.m');

set(groot, 'defaultTextInterpreter', 'latex');
set(groot, 'defaultAxesTickLabelInterpreter', 'latex');
set(groot, 'defaultLegendInterpreter', 'latex');

%% Simple shear flow
Pe = [1e1, 1e3, 1e5];
l = load(dataPath+"convergence_shear_steady.mat").l;
errs = load(dataPath+"convergence_shear_steady.mat").errs;
errsl2 = load(dataPath+"convergence_shear_steady.mat").errsl2;

figure(1);
hold on;
set(gca, 'Layer', 'top', 'LineWidth', 0.75, 'Box', 'on');
ylim([1e-16, 1])
xlim([0, 1000])
yscale('log');
ylabel("$\| \psi_\mathrm{ref}-\psi_{\ell_\mathrm{max}} \| \,/\, " + ...
       "\| \psi_\mathrm{ref} \|$", 'FontSize', 16)
xlabel('$\ell_\mathrm{max}$', 'FontSize', 16, 'Interpreter', 'latex')

for idx = 1:length(Pe)
    h1 = plot(l, errs(idx,:), 'LineWidth', 1.5, ...
        'DisplayName', sprintf('${Pe} = 10^{%d}$', log10(Pe(idx))));
    plot(l, errsl2(idx,:), '--', 'LineWidth', 1.5, 'Color', h1.Color, ...
        'HandleVisibility', 'off');
end

legend('show', ...
    'Interpreter', 'latex', ...
    'Location', 'northeast', ...
    'FontSize', 14);

labelAx = axes(gcf, ...
    'Position', [0 0 1 1], ...
    'Visible', 'off', ...
    'Units', 'normalized');
text(labelAx, -0.0, 1., '(a)', ...
    'Units', 'normalized', ...
    'Interpreter', 'latex', ...
    'FontSize', 20, ...
    'FontWeight', 'normal', ...
    'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'top', ...
    'Clipping', 'off');

set(gcf, 'Units', 'centimeters', 'Position', [5 5 14 9]);

exportgraphics(gcf,outputPath+"convergence_simple-shear.pdf", ...
               'ContentType','vector');


%% Planar extension flow
Pe = [1e0, 1e2, 1e4];
l = load(dataPath+"convergence_extension_steady.mat").l;
errs = load(dataPath+"convergence_extension_steady.mat").errs;
errsl2 = load(dataPath+"convergence_extension_steady.mat").errsl2;

figure(2);
hold on;
set(gca, 'Layer', 'top', 'LineWidth', 0.75, 'Box', 'on');
ylim([1e-16, 1e3])
xlim([0, 1000])
yscale('log');
ylabel("$\| \psi_\mathrm{ref}-\psi_{\ell_\mathrm{max}} \| \,/\, " + ...
       "\| \psi_\mathrm{ref} \|$", 'FontSize', 16)
xlabel('$\ell_\mathrm{max}$', 'FontSize', 16, 'Interpreter', 'latex')

for idx = 1:length(Pe)
    h1 = plot(l, errs(idx,:), 'LineWidth', 1.5, ...
        'DisplayName', sprintf('${Pe} = 10^{%d}$', log10(Pe(idx))));
    plot(l, errsl2(idx,:), '--', 'LineWidth', 1.5, 'Color', h1.Color, ...
        'HandleVisibility', 'off');
end

legend('show', ...
    'Interpreter', 'latex', ...
    'Location', 'northeast', ...
    'FontSize', 14);
labelAx = axes(gcf, ...
    'Position', [0 0 1 1], ...
    'Visible', 'off', ...
    'Units', 'normalized');
text(labelAx, -0.0, 1., '(b)', ...
    'Units', 'normalized', ...
    'Interpreter', 'latex', ...
    'FontSize', 20, ...
    'FontWeight', 'normal', ...
    'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'top', ...
    'Clipping', 'off');

set(gcf, 'Units', 'centimeters', 'Position', [5 5 14 9]);

exportgraphics(gcf,outputPath+"convergence_planar-extension.pdf", ...
               'ContentType','vector');